### ISSUE TITLE
Two Packages in Root Folder

### ISSUE THREAD

**Issue by SBrazzCode** [getzep/zep-go#1]
The 'zep' and 'main' package under zep-go causes compilation errors. The two packages have redefine constants i.e. APIBasePath, so they cannot be merged into one package.

There is likely a reason for overlapping constants, but in its current state, I can't get the main.go files to compile.

**Comment by SBrazzCode** [comment]
Closing for now, as I have a fix for this issue, but I can't create a pull request yet.

**Comment by danielchalef** [comment]
This is entirely possible. As mentioned the code is in a rough state 😉
