### ISSUE TITLE
sdk version 2 missing

### ISSUE THREAD

**Issue by matigumma** [getzep/zep-go#26]
![image](https://github.com/user-attachments/assets/3c17c344-9923-495d-9475-91f313727149)

**Comment by paul-paliychuk** [comment]
@matigumma my bad, need to update the readme. Mind trying `github.com/getzep/zep-go/v2`?

**Comment by matigumma** [comment]
tmc did not merge your update, right?
https://github.com/tmc/langchaingo/pull/746

**Comment by matigumma** [comment]
uhm i get it,...


las langchaingo version zep example is working only with 
zep 1.0.4 ...

if i update it to v2 miss: zep.MemoryGetRequestMemoryTypePerpetual

![image](https://github.com/user-attachments/assets/c137aa77-93b0-4c5c-b41a-ac773442f247)


![image](https://github.com/user-attachments/assets/881c24ea-b9f6-46d1-b6ad-e057d9fecf2c)

**Comment by paul-paliychuk** [comment]
@matigumma Hey, apologies for missing your last comment. We haven't made an update in langchain go yet for v2, it's on our roadmap.
